// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfPCBNgKdzbb4jbvAjJv5VtoPYNvnnOeE',
    appId: '1:199960507699:web:15d703df070c8639b23a46',
    messagingSenderId: '199960507699',
    projectId: 'newe-71410',
    authDomain: 'newe-71410.firebaseapp.com',
    storageBucket: 'newe-71410.firebasestorage.app',
    measurementId: 'G-ZR9ZBB9JT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRbeqC5DS4UTnnweR14XnbBeopsy8Tauw',
    appId: '1:199960507699:android:2aebcadda5589564b23a46',
    messagingSenderId: '199960507699',
    projectId: 'newe-71410',
    storageBucket: 'newe-71410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDt36zL8yKui6A7g4sb71R8LcHJEM3OMI',
    appId: '1:199960507699:ios:44b50ca7338aeaeab23a46',
    messagingSenderId: '199960507699',
    projectId: 'newe-71410',
    storageBucket: 'newe-71410.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJFtU-Wtp3P_Ms3ZGiLXvvcyI88hjjnDo',
    appId: '1:419173628101:ios:40e1d7d4df19a376fd18ac',
    messagingSenderId: '419173628101',
    projectId: 'kdserve-837ff',
    storageBucket: 'kdserve-837ff.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfPCBNgKdzbb4jbvAjJv5VtoPYNvnnOeE',
    appId: '1:199960507699:web:a3907734ebfdf5f6b23a46',
    messagingSenderId: '199960507699',
    projectId: 'newe-71410',
    authDomain: 'newe-71410.firebaseapp.com',
    storageBucket: 'newe-71410.firebasestorage.app',
    measurementId: 'G-ECB01487S3',
  );

}