// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3vJSDfB0D-26LEJp2aqF6qI5veRsz3tA',
    appId: '1:938345348500:web:b9ee47cdbea68e3a01e381',
    messagingSenderId: '938345348500',
    projectId: 'foodos-59233',
    authDomain: 'foodos-59233.firebaseapp.com',
    storageBucket: 'foodos-59233.firebasestorage.app',
    measurementId: 'G-D9FSKFQGDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WDCx1vW03UKASfQ_zgO84hc7Ki1UhSA',
    appId: '1:938345348500:android:b0318430d7402ef701e381',
    messagingSenderId: '938345348500',
    projectId: 'foodos-59233',
    storageBucket: 'foodos-59233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqNyiemlLmO4Fwyujq7SV656jHAWnyy0g',
    appId: '1:938345348500:ios:cc9c236af21be2f601e381',
    messagingSenderId: '938345348500',
    projectId: 'foodos-59233',
    storageBucket: 'foodos-59233.firebasestorage.app',
    iosClientId: '938345348500-hcfqofeqd6303qbqitoudlkqg8csb4o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqNyiemlLmO4Fwyujq7SV656jHAWnyy0g',
    appId: '1:938345348500:ios:cc9c236af21be2f601e381',
    messagingSenderId: '938345348500',
    projectId: 'foodos-59233',
    storageBucket: 'foodos-59233.firebasestorage.app',
    iosClientId: '938345348500-hcfqofeqd6303qbqitoudlkqg8csb4o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3vJSDfB0D-26LEJp2aqF6qI5veRsz3tA',
    appId: '1:938345348500:web:4d482e5e321ba2f001e381',
    messagingSenderId: '938345348500',
    projectId: 'foodos-59233',
    authDomain: 'foodos-59233.firebaseapp.com',
    storageBucket: 'foodos-59233.firebasestorage.app',
    measurementId: 'G-YC04P5RT4J',
  );

}